# Generated by Django 5.2 on 2025-04-24 19:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phno',
            field=models.CharField(max_length=250, validators=[django.core.validators.RegexValidator('^[+]?\\d+$')]),
        ),
    ]
