# Generated by Django 5.2 on 2025-04-24 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0004_music_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('phno', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='Music',
        ),
    ]
