# Generated by Django 5.2 on 2025-04-25 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0005_contact_delete_music'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(default=None, max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phno',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
